version: "3.7"
services:
  transporter:
    build:
      context: ./
      target: transporter
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      API_ADDR: "0.0.0.0:${API_PORT}"
      STATE_DIR: /app/state
      DB_CFG_PATH: /run/secrets/dbcfg
      SOLANA_KEYGEN_FILE: /run/secrets/solanakey
    restart: unless-stopped
    volumes:
      - /app/state
      - ${CONSENSUS_PATH}:/app/state/consensus
    secrets:
      - dbcfg
      - solanakey

secrets:
  dbcfg:
    file: dev-secrets/secrets.dbcfg
  solanakey:
    file: dev-secrets/secrets.solanakey
