// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package transporterdb

import (
	"database/sql"
)

type EmissionHistory struct {
	ID            int64
	AllowedSupply sql.NullInt64
	UpdateTime    sql.NullTime
	Tvl           sql.NullInt64
}

type PreminedWhitelist struct {
	ID      int64
	Address string
	Amount  int64
}

type TransportRecord struct {
	BurnID          string
	Address         string
	Amount          int64
	TotalSupply     sql.NullInt64
	BurnTime        sql.NullTime
	QueueUp         sql.NullTime
	InvoiceTime     sql.NullTime
	SolanaTxTime    sql.NullTime
	SolanaTxID      sql.NullString
	SolanaConfirmed bool
	Completed       bool
}
